//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLauncher.App.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English_Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English_Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLauncher.App.Languages.English_Texts", typeof(English_Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Entry Not Found.
        /// </summary>
        internal static string APIChecker_CacheEntryNotFound {
            get {
                return ResourceManager.GetString("APIChecker_CacheEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Failure.
        /// </summary>
        internal static string APIChecker_ConnectFailure {
            get {
                return ResourceManager.GetString("APIChecker_ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Closed.
        /// </summary>
        internal static string APIChecker_ConnectionClosed {
            get {
                return ResourceManager.GetString("APIChecker_ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timed Out.
        /// </summary>
        internal static string APIChecker_ConnectionTimeOut {
            get {
                return ResourceManager.GetString("APIChecker_ConnectionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetWay Time Out.
        /// </summary>
        internal static string APIChecker_GetWayTimeOut {
            get {
                return ResourceManager.GetString("APIChecker_GetWayTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SSL.
        /// </summary>
        internal static string APIChecker_InvaildSSL {
            get {
                return ResourceManager.GetString("APIChecker_InvaildSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Alive Failure.
        /// </summary>
        internal static string APIChecker_KeepAliveFailure {
            get {
                return ResourceManager.GetString("APIChecker_KeepAliveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Length Limit Exceeded.
        /// </summary>
        internal static string APIChecker_MessageLengthLimitExceeded {
            get {
                return ResourceManager.GetString("APIChecker_MessageLengthLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Resolution Failure.
        /// </summary>
        internal static string APIChecker_NameResolutionFailure {
            get {
                return ResourceManager.GetString("APIChecker_NameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string APIChecker_NotFound {
            get {
                return ResourceManager.GetString("APIChecker_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL was Null.
        /// </summary>
        internal static string APIChecker_Null {
            get {
                return ResourceManager.GetString("APIChecker_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string APIChecker_Offline {
            get {
                return ResourceManager.GetString("APIChecker_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string APIChecker_Online {
            get {
                return ResourceManager.GetString("APIChecker_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Unreachable.
        /// </summary>
        internal static string APIChecker_OriginUnreachable {
            get {
                return ResourceManager.GetString("APIChecker_OriginUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string APIChecker_Pending {
            get {
                return ResourceManager.GetString("APIChecker_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline Failure.
        /// </summary>
        internal static string APIChecker_PipelineFailure {
            get {
                return ResourceManager.GetString("APIChecker_PipelineFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Name Resolution Failure.
        /// </summary>
        internal static string APIChecker_ProxyNameResolutionFailure {
            get {
                return ResourceManager.GetString("APIChecker_ProxyNameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Failure.
        /// </summary>
        internal static string APIChecker_ReceiveFailure {
            get {
                return ResourceManager.GetString("APIChecker_ReceiveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Canceled.
        /// </summary>
        internal static string APIChecker_RequestCanceled {
            get {
                return ResourceManager.GetString("APIChecker_RequestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Prohibited By Cache Policy.
        /// </summary>
        internal static string APIChecker_RequestProhibitedByCachePolicy {
            get {
                return ResourceManager.GetString("APIChecker_RequestProhibitedByCachePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Channel Failure.
        /// </summary>
        internal static string APIChecker_SecureChannelFailure {
            get {
                return ResourceManager.GetString("APIChecker_SecureChannelFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Failure.
        /// </summary>
        internal static string APIChecker_SendFailure {
            get {
                return ResourceManager.GetString("APIChecker_SendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        internal static string APIChecker_ServerError {
            get {
                return ResourceManager.GetString("APIChecker_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Overloaded.
        /// </summary>
        internal static string APIChecker_ServerOverloaded {
            get {
                return ResourceManager.GetString("APIChecker_ServerOverloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Protocol Violation.
        /// </summary>
        internal static string APIChecker_ServerProtocolViolation {
            get {
                return ResourceManager.GetString("APIChecker_ServerProtocolViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Unavailable.
        /// </summary>
        internal static string APIChecker_ServerUnavailable {
            get {
                return ResourceManager.GetString("APIChecker_ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Failed.
        /// </summary>
        internal static string APIChecker_SSLFailed {
            get {
                return ResourceManager.GetString("APIChecker_SSLFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string APIChecker_Success {
            get {
                return ResourceManager.GetString("APIChecker_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Out.
        /// </summary>
        internal static string APIChecker_Timeout {
            get {
                return ResourceManager.GetString("APIChecker_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust Failure.
        /// </summary>
        internal static string APIChecker_TrustFailure {
            get {
                return ResourceManager.GetString("APIChecker_TrustFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string APIChecker_Unknown {
            get {
                return ResourceManager.GetString("APIChecker_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Status Code.
        /// </summary>
        internal static string APIChecker_UnknownStatusCode {
            get {
                return ResourceManager.GetString("APIChecker_UnknownStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBRW Launcher will have to Close due to a Thread Exception.
        /// </summary>
        internal static string Application_Exception_Thread {
            get {
                return ResourceManager.GetString("Application_Exception_Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBRW Launcher will have to Close due to a Unhandled Exception.
        /// </summary>
        internal static string Application_Exception_Unhandled {
            get {
                return ResourceManager.GetString("Application_Exception_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Global_Text_About {
            get {
                return ResourceManager.GetString("Global_Text_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete.
        /// </summary>
        internal static string Global_Text_EG_1 {
            get {
                return ResourceManager.GetString("Global_Text_EG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETA Build Date.
        /// </summary>
        internal static string KitEnabler_Beta {
            get {
                return ResourceManager.GetString("KitEnabler_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEV Build Date.
        /// </summary>
        internal static string KitEnabler_Dev {
            get {
                return ResourceManager.GetString("KitEnabler_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Date.
        /// </summary>
        internal static string KitEnabler_Public {
            get {
                return ResourceManager.GetString("KitEnabler_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Web Browser has been opened to the Game Launcher&apos;s GitHub Latest Release Page to Download the New Version.
        /// </summary>
        internal static string LauncherUpdateCheck_FS {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_FS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Status:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Beta {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Dev {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Text_Build {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Text_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Text_Current {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Text_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Text_Stable {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Text_Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unofficial.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Insider_Unofficial {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Insider_Unofficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Status:\n- API Version Error.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Invalid_Error {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Invalid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Status:\n- Invalid JSON.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Invalid_JSON {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Invalid_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Status:\n- Current Version.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_No_Update {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_No_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Status:\n- Update Available.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Update {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Update_New {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Update_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string LauncherUpdateCheck_VS_Text_Version {
            get {
                return ResourceManager.GetString("LauncherUpdateCheck_VS_Text_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Forgot My Password.
        /// </summary>
        internal static string MainScreen_Button_Forgot_Password {
            get {
                return ResourceManager.GetString("MainScreen_Button_Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        internal static string MainScreen_Button_Launch {
            get {
                return ResourceManager.GetString("MainScreen_Button_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MainScreen_Button_Login {
            get {
                return ResourceManager.GetString("MainScreen_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Now.
        /// </summary>
        internal static string MainScreen_Button_Play {
            get {
                return ResourceManager.GetString("MainScreen_Button_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string MainScreen_Button_Register {
            get {
                return ResourceManager.GetString("MainScreen_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Server.
        /// </summary>
        internal static string MainScreen_Button_SelectServer {
            get {
                return ResourceManager.GetString("MainScreen_Button_SelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Launcher.
        /// </summary>
        internal static string MainScreen_Context_Close {
            get {
                return ResourceManager.GetString("MainScreen_Context_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is going to shut down in 5 minutes. Please restart it manually before the launcher does it..
        /// </summary>
        internal static string MainScreen_Notification_Text_Alert {
            get {
                return ResourceManager.GetString("MainScreen_Notification_Text_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Restart -.
        /// </summary>
        internal static string MainScreen_Notification_Text_Restart {
            get {
                return ResourceManager.GetString("MainScreen_Notification_Text_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Invite.
        /// </summary>
        internal static string MainScreen_Text_AccountLink_Discord {
            get {
                return ResourceManager.GetString("MainScreen_Text_AccountLink_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Group.
        /// </summary>
        internal static string MainScreen_Text_AccountLink_Facebook {
            get {
                return ResourceManager.GetString("MainScreen_Text_AccountLink_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string MainScreen_Text_AccountLink_Home {
            get {
                return ResourceManager.GetString("MainScreen_Text_AccountLink_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Feed.
        /// </summary>
        internal static string MainScreen_Text_AccountLink_Twitter {
            get {
                return ResourceManager.GetString("MainScreen_Text_AccountLink_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main API\n- Pinging.
        /// </summary>
        internal static string MainScreen_Text_API_Launcher {
            get {
                return ResourceManager.GetString("MainScreen_Text_API_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher is Offline.
        /// </summary>
        internal static string MainScreen_Text_API_Launcher_Description_Offline {
            get {
                return ResourceManager.GetString("MainScreen_Text_API_Launcher_Description_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to API.
        /// </summary>
        internal static string MainScreen_Text_API_Launcher_Description_Online {
            get {
                return ResourceManager.GetString("MainScreen_Text_API_Launcher_Description_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Online: ###\nRegistered: ###.
        /// </summary>
        internal static string MainScreen_Text_API_Server {
            get {
                return ResourceManager.GetString("MainScreen_Text_API_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Status:\n - Linux Build.
        /// </summary>
        internal static string MainScreen_Text_FS_Launcher_Status_Linux {
            get {
                return ResourceManager.GetString("MainScreen_Text_FS_Launcher_Status_Linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pshhh Pshhh.
        /// </summary>
        internal static string MainScreen_Text_FS_Login_Greeting {
            get {
                return ResourceManager.GetString("MainScreen_Text_FS_Login_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher\n- Checking.
        /// </summary>
        internal static string MainScreen_Text_Launcher_Status {
            get {
                return ResourceManager.GetString("MainScreen_Text_Launcher_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: v.
        /// </summary>
        internal static string MainScreen_Text_Launcher_Version {
            get {
                return ResourceManager.GetString("MainScreen_Text_Launcher_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Account Information to Login.
        /// </summary>
        internal static string MainScreen_Text_Login {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Afternoon.
        /// </summary>
        internal static string MainScreen_Text_Login_Greeting_Afternoon {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login_Greeting_Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening.
        /// </summary>
        internal static string MainScreen_Text_Login_Greeting_Evening {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login_Greeting_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning.
        /// </summary>
        internal static string MainScreen_Text_Login_Greeting_Morning {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login_Greeting_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Night Owl.
        /// </summary>
        internal static string MainScreen_Text_Login_Greeting_YouNeedSleep {
            get {
                return ResourceManager.GetString("MainScreen_Text_Login_Greeting_YouNeedSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insider Build Date: ##-##-##-X.
        /// </summary>
        internal static string MainScreen_Text_PH_InsiderBuildNumber {
            get {
                return ResourceManager.GetString("MainScreen_Text_PH_InsiderBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: vX.X.X.X.
        /// </summary>
        internal static string MainScreen_Text_PH_Launcher_Version {
            get {
                return ResourceManager.GetString("MainScreen_Text_PH_Launcher_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: Default Text.
        /// </summary>
        internal static string MainScreen_Text_PH_SceneryGroup_Default {
            get {
                return ResourceManager.GetString("MainScreen_Text_PH_SceneryGroup_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        internal static string MainScreen_Text_PlayProgress {
            get {
                return ResourceManager.GetString("MainScreen_Text_PlayProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Hidden.
        /// </summary>
        internal static string MainScreen_Text_Protection_Email {
            get {
                return ResourceManager.GetString("MainScreen_Text_Protection_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: Christmas.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Christmas {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Christmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But It&apos;s Me!.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_EG_1 {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_EG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: Halloween.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Halloween {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Halloween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: New Years.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_NewYears {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_NewYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: Normal.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Normal {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: Oktoberfest.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Oktoberfest {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Oktoberfest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenery: Valentines.
        /// </summary>
        internal static string MainScreen_Text_SceneryGroup_Valentines {
            get {
                return ResourceManager.GetString("MainScreen_Text_SceneryGroup_Valentines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ping to the Server.
        /// </summary>
        internal static string MainScreen_Text_ServerPingStatus {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerPingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay Timer:.
        /// </summary>
        internal static string MainScreen_Text_ServerShutDown {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Launcher!.
        /// </summary>
        internal static string MainScreen_Text_ServerShutDown_EG_1 {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerShutDown_EG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status:\n - Pinging.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Checking {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Connect to Server.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Description_Cancelled {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Description_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Seems to be Offline.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Description_Offline {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Description_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online: {0}\nRegistered: {1}.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Description_Online {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Description_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recevied Invalid JSON Game Server Info..
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Description_Unstable {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Description_Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status:\n - Offline ( OFF ).
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Offline {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status:\n - Online ( ON ).
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Online {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Offline:\n - Unknown.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Unknown {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Connection:\n - Unstable.
        /// </summary>
        internal static string MainScreen_Text_ServerStatus_Unstable {
            get {
                return ResourceManager.GetString("MainScreen_Text_ServerStatus_Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the GameLauncher is still downloading the game files..
        /// </summary>
        internal static string MainScreen_TextBox_GameFiles_Downloading {
            get {
                return ResourceManager.GetString("MainScreen_TextBox_GameFiles_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive {0} was not found. Your actual installation directory is set to {1} now..
        /// </summary>
        internal static string MainScreen_TextBox_GameFiles_Invalid_Location {
            get {
                return ResourceManager.GetString("MainScreen_TextBox_GameFiles_Invalid_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Screen Encountered an Error.
        /// </summary>
        internal static string MainScreen_TextBox_SettingsScreen_Error {
            get {
                return ResourceManager.GetString("MainScreen_TextBox_SettingsScreen_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string Program_TextBox_File_Invalid {
            get {
                return ResourceManager.GetString("Program_TextBox_File_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Architecture.
        /// </summary>
        internal static string Program_TextBox_File_Invalid_CPU {
            get {
                return ResourceManager.GetString("Program_TextBox_File_Invalid_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Start GameLauncher.\nThe following files are invalid:\n\n.
        /// </summary>
        internal static string Program_TextBox_File_Invalid_Start {
            get {
                return ResourceManager.GetString("Program_TextBox_File_Invalid_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Version.
        /// </summary>
        internal static string Program_TextBox_File_Invalid_Version {
            get {
                return ResourceManager.GetString("Program_TextBox_File_Invalid_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string Program_TextBox_File_NotFound {
            get {
                return ResourceManager.GetString("Program_TextBox_File_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using this location for GameLauncher is not allowed..
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following locations are also NOT allowed:.
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P2 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Root of Drive, such as C:\\ or D:\\, must be in a folder).
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P3 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Includes &apos;Desktop&apos;, &apos;Documents&apos;, &apos;Downloads&apos;).
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P4 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead, move the Launcher folder to someplace like:.
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P5 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P6 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Or any other NTFS &apos;Local Disk&apos; location such as &apos;D:&apos;).
        /// </summary>
        internal static string Program_TextBox_Folder_Check_Launcher_P7 {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Check_Launcher_P7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to do a Test Write to Launcher Folder.\nPermission Issue.
        /// </summary>
        internal static string Program_TextBox_Folder_Write_Test {
            get {
                return ResourceManager.GetString("Program_TextBox_Folder_Write_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of Need for Speed: World is already running.
        /// </summary>
        internal static string Program_TextBox_GameIsRunning {
            get {
                return ResourceManager.GetString("Program_TextBox_GameIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded Missing LZMA.dll File.\nPlease Restart Launcher, Thanks!.
        /// </summary>
        internal static string Program_TextBox_LZMA_Redownloaded {
            get {
                return ResourceManager.GetString("Program_TextBox_LZMA_Redownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires a minimum version of the .NET Framework:\n.
        /// </summary>
        internal static string Program_TextBox_NetFrame_P1 {
            get {
                return ResourceManager.GetString("Program_TextBox_NetFrame_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install this .NET Framework version now?.
        /// </summary>
        internal static string Program_TextBox_NetFrame_P2 {
            get {
                return ResourceManager.GetString("Program_TextBox_NetFrame_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application could not be started..
        /// </summary>
        internal static string Program_TextBox_NetFrame_P3 {
            get {
                return ResourceManager.GetString("Program_TextBox_NetFrame_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of SBRW Launcher is already running.
        /// </summary>
        internal static string Program_TextBox_SBRWIsRunning {
            get {
                return ResourceManager.GetString("Program_TextBox_SBRWIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of SBRW Simplified Launcher is already running.
        /// </summary>
        internal static string Program_TextBox_SimplifiedIsRunning {
            get {
                return ResourceManager.GetString("Program_TextBox_SimplifiedIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System Detection Check Encountered an Error..
        /// </summary>
        internal static string Program_TextBox_System_Detection {
            get {
                return ResourceManager.GetString("Program_TextBox_System_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey Windows 7 User, we&apos;ve detected a potential issue of some missing Updates that are required..
        /// </summary>
        internal static string Program_TextBox_W7_TLS_P1 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_TLS_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found that these Windows Update packages are showing as not installed:.
        /// </summary>
        internal static string Program_TextBox_W7_TLS_P2 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_TLS_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Program_TextBox_W7_TLS_P3 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_TLS_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aditionally, we must add a value to the registry:.
        /// </summary>
        internal static string Program_TextBox_W7_TLS_P4 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_TLS_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add those values?.
        /// </summary>
        internal static string Program_TextBox_W7_KB_P1 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_KB_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry option set, Remember that the changes may require a system reboot to take effect.
        /// </summary>
        internal static string Program_TextBox_W7_KB_P2 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_KB_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roger that, There may be some issues connecting to the servers..
        /// </summary>
        internal static string Program_TextBox_W7_KB_P3 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_KB_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roger that, There may be some issues connecting to the servers..
        /// </summary>
        internal static string Program_TextBox_W7_KB_P4 {
            get {
                return ResourceManager.GetString("Program_TextBox_W7_KB_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the 32-bit 2015-2019 VC++ Redistributable Package installed..
        /// </summary>
        internal static string Redistributable_VC_32 {
            get {
                return ResourceManager.GetString("Redistributable_VC_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the 64-bit 2015-2019 VC++ Redistributable Package installed..
        /// </summary>
        internal static string Redistributable_VC_64 {
            get {
                return ResourceManager.GetString("Redistributable_VC_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download package installer.\nThe game will not be started..
        /// </summary>
        internal static string Redistributable_VC_P10 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will install in the Background.
        /// </summary>
        internal static string Redistributable_VC_P2 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may restart your computer..
        /// </summary>
        internal static string Redistributable_VC_P3 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to install it..
        /// </summary>
        internal static string Redistributable_VC_P4 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        internal static string Redistributable_VC_P5 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run package installer.\n The game will not be started..
        /// </summary>
        internal static string Redistributable_VC_P6 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run package installer.\n Installer Exit Code.
        /// </summary>
        internal static string Redistributable_VC_P7 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game will not be started..
        /// </summary>
        internal static string Redistributable_VC_P8 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start package installer.\n The game will not be started..
        /// </summary>
        internal static string Redistributable_VC_P9 {
            get {
                return ResourceManager.GetString("Redistributable_VC_P9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Connect to any Server List API.\nPlease check your connection.\n\nClick Yes to Close Launcher\n\nor\n\nClick No Continue.
        /// </summary>
        internal static string VisualsAPIChecker_TextBox_No_API {
            get {
                return ResourceManager.GetString("VisualsAPIChecker_TextBox_No_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameLauncher has Stopped, Failed To Connect to any Server List API.
        /// </summary>
        internal static string VisualsAPIChecker_TextBox_No_API_P2 {
            get {
                return ResourceManager.GetString("VisualsAPIChecker_TextBox_No_API_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please keep in Mind Launcher might crash past this point.\nMake sure to resolve the issue next time.
        /// </summary>
        internal static string VisualsAPIChecker_TextBox_No_API_P3 {
            get {
                return ResourceManager.GetString("VisualsAPIChecker_TextBox_No_API_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameLauncher will continue, despite failing To Connect To API.
        /// </summary>
        internal static string VisualsAPIChecker_TextBox_No_API_P4 {
            get {
                return ResourceManager.GetString("VisualsAPIChecker_TextBox_No_API_P4", resourceCulture);
            }
        }
    }
}
